config/urls.py
from django.contrib import admin
from django.urls import path, include
import user
import content
from django.conf.urls.static import static
from .settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', include('content.urls')),
]
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

content/urls.py
from django.urls import path
from . import views
app_name = 'content'
urlpatterns = [
    path('', views.Main.as_view(), name='index'),
    path('content/profile', views.Profile.as_view(), name='profile'),
    path('content/upload',views.UploadFeed.as_view(), name='upload_feed'),
    path('like/<int:id>', views.like_count, name='like_count')
]

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user'
urlpatterns = [
    path('join', views.Join.as_view(), name='join'),
    path('login', views.Login.as_view(), name='login'),
    path('logout', views.LogOut.as_view(), name='logout'),
    path('profile/upload', views.UploadProfile.as_view(), name='profileUpload'),
]

content/models.py
from django.db import models
from user.models import User
# Create your models here.
class Feed(models.Model):
    email = models.ForeignKey(User, on_delete=models.CASCADE, related_name='email_feed') # 글쓴이
    content = models.TextField()    # 글내용
    image = models.TextField()  # 피드 이미지
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    likes = models.ManyToManyField(User, related_name='likes_feed')

    def __str__(self):
        return self.content
    class Meta:
        ordering=['-create_date']

class Reply(models.Model):
    email = models.ForeignKey(User, on_delete=models.CASCADE, related_name='email_reply') # 글쓴이
    feed_id = models.ForeignKey(Feed,on_delete=models.CASCADE, related_name='feed_reply')
    reply_content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    class Meta:
        ordering=['-create_date']

class Bookmark(models.Model):
    feed_id = models.ForeignKey(Feed,on_delete=models.CASCADE, related_name='feed_bookmark')
    email = models.ForeignKey(User, on_delete=models.CASCADE, related_name='email_bookmark') # 글쓴이
    is_marked = models.BooleanField(default=True)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    class Meta:
        ordering=['-create_date']

content/views.py
import email
from multiprocessing import context
import profile
from uuid import uuid4
from django.shortcuts import redirect, render
from rest_framework.views import APIView
from rest_framework.response import Response
from .models import *
from config import settings
import os
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages


# Create your views here.
# def index(request):
#     return render(request,'content/main.html')
# def profile(request):
#     return render(request,'content/profile.html')
class Main(APIView):
    def get(self, request):
        feed_list = Feed.objects.all()
        context = dict(feed_list=feed_list)
        return render(request, 'content/main.html', context=context)

class Profile(APIView):
    def get(self, request):
        feed_count = Feed.objects.filter(email=request.user).count()
        context = {'feed_count':feed_count}
        return render(request, 'content/profile.html', context=context)

class UploadFeed(APIView):
    def post(self, request):
        file = request.FILES['file']
        uuid_name = uuid4().hex
        save_path = os.path.join(settings.MEDIA_ROOT, uuid_name)
        with open(save_path, 'wb+') as destination:
            for chunk in file.chunks():
                destination.write(chunk)
        content = request.data.get('content')
        image = uuid_name
        user_id = request.data.get('user_id')
        create_date = timezone.now()
        user = User.objects.get(email='hans')#[0]
        Feed.objects.create(email=user, content=content,image=image, create_date=create_date)
        return Response(status=200)

@login_required(login_url='user:login')    
def like_count(request, id):
    feed = Feed.objects.get(id=id)
    if request.user.username == feed.email.username:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        if feed.likes.filter(email=request.user):
            feed.likes.remove(request.user)
        else:
            feed.likes.add(request.user)
    return redirect('content:index')

templates/content/main.html
{% extends 'common/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/style_main.css'%}">

<div class="main_body">
    <div class="left_body">
        
        {% for feed in feed_list %}
        <div class="border feed_box">
            <div class="feed_name">
                <div class="profile_box">
                    <img class="profile_img" src="{% get_media_prefix%}{{feed.email.profile_image}}">
                </div>
                <span class="feed_name_txt"> {{feed.email.nickname}}</span>
            </div>
            <img class="feed_img " src="{% get_media_prefix%}{{feed.image}}">
            <div class="feed_icon">
                <div>
                    <a href="{% url 'content:like_count' feed.id %}"><span class="material-icons-outlined">
                            favorite_border
                        </span>
                    </a>
                    <span class="material-icons-outlined">
                        mode_comment
                    </span>
                    <span class="material-icons-outlined">
                        send
                    </span>
                </div>
                <div>
                    <span class="material-icons-outlined">
                        turned_in_not
                    </span>
                </div>
            </div>
            
            <div class="feed_like">
                
                <input type="hidden" value="{{feed.id}}">
                <p class="feed_txt"> <b>좋아요 {{feed.likes.count}} 개
                    </b></p>
            </div>
            <div class="feed_content">
                <p class="feed_txt"> <b>{{user.nickname}} </b>{{feed.content}}</p>
            </div>
            <!-- <div class="feed_reply">
                <span class="feed_txt"> <b> mychew </b> 제주도 가고 싶어요 ㅠㅠ</span>
                <span class="feed_txt"> <b> cho </b> 제주도 ㄱ ㄱ </span>

            </div> -->
        </div>
        {% endfor %}
    </div>
    <div class="right_body">
        {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
            {%for message in messages%}
            <strong>{{message.tag}}</strong>
            <ul>
                <li>{{message.message}}</li>
            </ul>
            {%endfor%}
        </div>
        {%endif%}
        <div class="feed_name" style="justify-content: space-between;">
            <div style="display: flex; align-items:center;">
                <!-- 사용자 오류 표시 -->
                {% if user.is_authenticated %}
                <div class="big_profile_box">
                    <img class="profile_img" src="{% get_media_prefix%}{{user.profile_image}}">
                </div>
                <div class="name_content">
                    <span class="feed_name_txt">{{user.nickname}}</span>
                    <span class="name_content_txt">{{user.nickname}}</span>
                </div>
                {%else%}
                <div class="big_profile_box">
                    <img class="profile_img" src="{% static 'img/django.png'%}">
                </div>
                <div class="name_content">
                    <span class="feed_name_txt">{{user.nickname}}</span>
                    <span class="name_content_txt">{{user.nickname}}</span>
                </div>
                {%endif%}
            </div>
        </div>

        <div class="recommend_box">
            <span style="color: gray">회원님을 위한 추천</span>
            <span style="font-size: 12px;">모두 보기</span>
        </div>
        <div>
            <div class="feed_name" style="justify-content: space-between">
                <div class="profile_box">
                    <img class="profile_img"
                        src="https://i.pinimg.com/736x/93/a6/8b/93a68b57a54e4bdc73d43d1d049b94b3.jpg">
                </div>
                <div class="name_content">
                    <span class="feed_name_txt"> dation3388 </span>
                    <span class="name_content_txt"> Jinstargram </span>
                </div>
                <a class="link_txt btn btn-primary">
                    팔로우
                </a>
            </div>

            <div class="feed_name" style="justify-content: space-between">
                <div class="profile_box">
                    <img class="profile_img"
                        src="http://file3.instiz.net/data/cached_img/upload/2021/01/27/18/2ce2f41f7e9f09c0acc77faac7452dbf.jpg">
                </div>
                <div class="name_content">
                    <span class="feed_name_txt"> gaoudi </span>
                    <span class="name_content_txt"> IU 외 5명이 팔로우</span>
                </div>
                <a class="link_txt btn btn-primary">
                    팔로우
                </a>
            </div>
        </div>
        <div class="comment_box">
            <span> 인스타그램 클론 코딩 </span>
            <span> Multicampus Hanstagram </span>
            <br>
            <span> 2022 09 29 </span>

        </div>
    </div>
</div>
<!-- modal1 -->
<div id='first_modal' class="modal_overlay">
    <div class="modal_window">
        <div class="modal_title">
            <div class="modal_title_side"></div>
            <div>새 게시물</div>
            <div class="modal_title_side">
                <span class="material-icons-outlined close_modal">
                    close
                </span>
            </div>
        </div>
        <div class="modal_image_upload">
            <span style="text-align: center"> 사진을 여기에 끌어다 놓으세요. </span>
        </div>
    </div>
</div>

<!-- modal2 -->
<div id="second_modal" class="modal modal_overlay">
    <div class="modal_window">
        <div class="modal_title">
            <div class="modal_title_side"></div>
            <div>새 게시물</div>
            <div class="modal_title_side">
                <span class="material-icons-outlined close_modal">
                    close
                </span>
            </div>
        </div>
        <div class="modal_image_content">
            <div id="input_image" class="modal_image_upload_content">

            </div>
            <div class="modal_content_write">
                <div class="feed_name">
                    <div class="profile_box">
                        <img id="input_profile_image" class="profile_img"
                            src="{%get_media_prefix%}{{user.profile_image}}">
                    </div>
                    <span id="" class="feed_name_txt"> {{user.nickname}} </span>
                    <input type="hidden" id="input_user_id" value="{{user.email}}">
                </div>
                <div style="height: 440px">
                    <textarea id="input_content" class="feed_content_textarea form-control col-sm-5" rows="10"
                        placeholder="설명을 입력하세요..."></textarea>
                </div>
                <div style="width: 100%; text-align: center">
                    <button id="button_write_feed" type="button" class="btn btn-primary" style="width: 268px">
                        공유하기</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    let files;
    const modal = document.getElementById("first_modal");
    const buttonAddFeed = document.getElementById("nav_bar_add_box");
    buttonAddFeed.addEventListener("click", e => {
        modal.style.top = window.pageYOffset + 'px';
        modal.style.display = 'flex';
        document.body.style.overflowY = 'hidden';
    });

    $(".close_modal").click(function () {
        $('#first_modal').css({
            display: 'none'
        });
        $('#second_modal').css({
            display: 'none'
        });
    });

    $('.modal_image_upload')
        .on("dragover", dragOver)
        .on("dragleave", dragOver)
        .on("drop", uploadFiles);

    function dragOver(e) {
        e.stopPropagation();
        e.preventDefault();

        if (e.type == "dragover") {
            $(e.target).css({
                "background-color": "black",
                "outline-offset": "-20px"
            });
        } else {
            $(e.target).css({
                "background-color": "white",
                "outline-offset": "-10px"
            });
        }
    };
    function uploadFiles(e) {
        e.stopPropagation();
        e.preventDefault();

        e.dataTransfer = e.originalEvent.dataTransfer;
        files = e.target.files || e.dataTransfer.files;
        console.log("뭔가 파일을 올렸네??" + files[0].name);

        if (files.length > 1) {
            alert('파일 하나만 올려주세요!');
            return;
        }

        if (files[0].type.match(/image.*/)) {
            $('#second_modal').css({ display: 'flex' });
            $('.modal_image_upload_content').css({
                "background-image": "url(" + window.URL.createObjectURL(files[0]) + ")",
                "outline": "none",
                "background-size": "contain",
                "background-repeat": "no-repeat",
                "background-position": "center"
            });
            $('#first_modal').css({
                display: 'none'
            })
        } else {
            alert('이미지가 아닙니다.');
            return;
        }
    };

    $('#button_write_feed').on('click', () => {
        const image = $('#input_image').css("background-image").replace(/^url\(['"](.+)['"]\)/, '$1');
        const content = $('#input_content').val();
        // const profile_image = $('#input_profile_image').attr('src');
        const user_id = $('#input_user_id').val();

        const file = files[0];

        let fd = new FormData();

        fd.append('file', file);
        fd.append('image', image);
        fd.append('content', content);
        // fd.append('profile_image', profile_image);
        fd.append('user_id', user_id);
        fd.append('csrfmiddlewaretoken', "{{ csrf_token }}")
        if (image.length <= 0) {
            alert("이미지가 비어있습니다.");
        }
        else if (content.length <= 0) {
            alert("설명을 입력하세요");
        }

        else if (user_id.length <= 0) {
            alert("사용자 id가 없습니다.");
        }
        else {
            writeFeed(fd);
            console.log(files[0]);
        }
    });

    function writeFeed(fd) {
        $.ajax({
            url: "/content/upload",
            data: fd,
            method: "POST",
            processData: false,
            contentType: false,
            success: function (data) {
                console.log("성공");
            },
            error: function (request, status, error) {
                console.log("에러");
            },
            complete: function () {
                console.log("무조건실행");
                location.reload();
            }
        })
    };
</script>
{%endblock%}

templates/content/profile.html
{% extends 'common/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/style.css'%}">

<div style="display: flex; flex-direction: row;text-align: center; justify-content: center;padding-top: 60px; background-color:#FAFAFA">
    <div style="padding: 20px 60px">
        <div class="box" style="width: 175px; height: 175px;">
            <img class="profile"
                 src="{% get_media_prefix %}{{ user.profile_image }}">
                 

        </div>
    </div>
    <div style="text-align: left">
        <div style="display: flex; flex-direction: row; margin: 20px 0">
            <div style="font-size: 26px; margin-right: 40px">
                {{ user.nickname }}<br>
            </div>
            <button id="button_profile_upload" style="margin-right: 40px" class="btn btn-outline-dark"> 프로필 사진 편집</button>
            <input type="file" id="input_fileupload" onchange="profile_upload();" style="display: none" />
            <!-- <span class="material-icons-outlined" style="margin-right: 40px">settings</span> -->
        </div>

        <div style="margin-bottom: 20px">
            게시물 내 게시물건수 {{feed_count}} 팔로워 111 팔로잉 111
         
        </div>
        <div>
            <b>{{ user.name }}</b>
        </div>
    </div>
</div>
<div style="border-top: solid 2px rgba(50,50,50,0.1); width: 100%">

    <div style="display: flex; flex-direction: row; justify-content: center; align-items: center; margin: 20px">
        <div id="button_feed_list" style="cursor: pointer;margin: 0 30px;display: flex; flex-direction: row;align-items: center"><span class="material-icons-outlined">grid_on</span>내 게시물</div>
        <div id="button_feed_like_list" style="cursor: pointer;margin: 0 30px;display: flex; flex-direction: row;align-items: center"><span class="material-icons-outlined">favorite_border</span>좋아요</div>
        <div id="button_feed_bookmark_list" style="cursor: pointer;margin: 0 30px;display: flex; flex-direction: row;align-items: center"><span class="material-icons-outlined">bookmark_border</span>북마크</div>
    </div>

</div>
<div id="feed_list" style="width: 100%; min-width: 1000px; display: flex; align-items: center;justify-content: center">
    <div style="display: flex; flex-direction: row; flex-wrap: wrap; width: 1000px; justify-content: center">
        {% for feed in feed_list %}
            <div style="width: 300px;height: 300px; margin: 10px 5px 0px 5px;">

                <div><img style="width: 300px;height: 300px; object-fit: cover"
                          src="https://shop-phinf.pstatic.net/20220124_58/1643007905108LRI7J_JPEG/MSB2US1201LGR_MDL.JPG?type=ff500_500">
                </div>
            </div>
        {% endfor %}
    </div>
</div>
<div id="like_feed_list" style="width: 100%; min-width: 1000px; display: none; align-items: center;justify-content: center">
    <div style="display: flex; flex-direction: row; flex-wrap: wrap; width: 1000px; justify-content: center">
        {% for feed in like_feed_list %}
            <div style="width: 300px;height: 300px; margin: 10px 5px 0px 5px;">

                <div><img style="width: 300px;height: 300px; object-fit: cover"
                          src="https://shop-phinf.pstatic.net/20220124_58/1643007905108LRI7J_JPEG/MSB2US1201LGR_MDL.JPG?type=ff500_500">
                </div>
            </div>
        {% endfor %}
    </div>
</div>

<div id="bookmark_feed_list" style="width: 100%; min-width: 1000px; display: none; align-items: center;justify-content: center">
    <div style="display: flex; flex-direction: row; flex-wrap: wrap; width: 1000px; justify-content: center">
        {% for feed in bookmark_feed_list %}
            <div style="width: 300px;height: 300px; margin: 10px 5px 0px 5px;">

                <div><img style="width: 300px;height: 300px; object-fit: cover"
                          src="https://shop-phinf.pstatic.net/20220124_58/1643007905108LRI7J_JPEG/MSB2US1201LGR_MDL.JPG?type=ff500_500">
                </div>
            </div>
        {% endfor %}
    </div>
</div>
<!-- 첫번째 모달 -->
<div id="first_modal" class="modal_overlay">
    <div class="modal_window">
        <div style="display: flex; flex-direction: row; justify-content: space-between">
            <div style="width: 40px; background: gray">

            </div>
            <div>
                새 이미지 업로드
            </div>
            <div style="width: 40px; background: gray">
                <span class="modal_close material-icons-outlined">close</span>
            </div>
        </div>

        <div class="img_upload_space" style="border-top: solid 1px gray;width: 778px; height: 540px;margin-top: 10px">

        </div>
    </div>
</div>

<!-- 두번째 모달 -->
<div id="second_modal" class="modal_overlay">
    <div class="modal_window">
        <div style="display: flex; flex-direction: row; justify-content: space-between">
            <div style="width: 40px; background: gray">

            </div>
            <div>
                새 이미지 업로드
            </div>
            <div style="width: 40px; background: gray">
                <span class="modal_close material-icons-outlined">close</span>
            </div>
        </div>

        <div style="border-top: solid 1px gray;display: flex; flex-direction: row;margin-top: 10px">
            <div class="img_upload_space" style="width: 500px; height: 540px;">

            </div>
            <div style="border-left: solid 1px gray">
                <div>
                    <textarea id="input_feed_content" class="form-control" style="width: 276px; height: 400px"
                              id="exampleFormControlTextarea1" rows="5"></textarea>
                </div>
                <button id="feed_create_button" type="button" class="btn btn-primary" style="width: 100%">
                    공유하기
                </button>
            </div>

        </div>

    </div>
</div>
<!-- javascript는 마지막에 넣어야 동작되는구나 -->
<script>
    function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

var csrftoken = getCookie('csrftoken');

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});
    $("#button_feed_list").click(function (){
    $('#feed_list').css({
        display : 'flex'
    });
    $('#like_feed_list').css({
        display : 'none'
    });
    $('#bookmark_feed_list').css({
        display : 'none'
    });
});
$("#button_feed_like_list").click(function (){
    $('#feed_list').css({
        display : 'none'
    });
    $('#like_feed_list').css({
        display : 'flex'
    });
    $('#bookmark_feed_list').css({
        display : 'none'
    });
});
$("#button_feed_bookmark_list").click(function (){
    $('#feed_list').css({
        display : 'none'
    });
    $('#like_feed_list').css({
        display : 'none'
    });
    $('#bookmark_feed_list').css({
        display : 'flex'
    });
});



$(".modal_close").click(function () {
    $('#first_modal').css({
        display: 'none'
    });
    $('#second_modal').css({
        display: 'none'
    });
});

let files;

$('#nav_bar_add_box').click(function () {
    $('#first_modal').css({
        display: 'flex'
    });

    $(document.body).css({
        overflow: 'hidden'
    });

});

$('#feed_create_button').click(function () {
    alert("공유하기 눌렀다.");

    let file = files[0];
    let image = files[0].name;
    let content = $('#input_feed_content').val();

    let fd = new FormData();

    fd.append('file', file);
    fd.append('image', image);
    fd.append('content', content);

    $.ajax({
        url: "/content/upload",
        data: fd,
        method: "POST",
        processData: false,
        contentType: false,
        success: function (data) {
            console.log("성공");
        },
        error: function (request, status, error) {
            console.log("에러");
        },
        complete: function () {
            console.log("완료");
            location.replace("/main");
        }
    });
});

$('.img_upload_space')
    .on("dragover", dragOver)
    .on("dragleave", dragOver)
    .on("drop", uploadFiles);

function dragOver(e) {
    e.stopPropagation();
    e.preventDefault();

    if (e.type == "dragover") {
        $(e.target).css({
            "background-color": "black",
            "outline-offset": "-20px"
        });
    } else {
        $(e.target).css({
            "outline-offset": "-10px"
        });
    }
}

function uploadFiles(e) {
    e.stopPropagation();
    e.preventDefault();

    e.dataTransfer = e.originalEvent.dataTransfer; //2
    files = e.target.files || e.dataTransfer.files;
    console.log("뭔가 파일을 올렸네??" + files[0].name);
    if (files.length > 1) {
        alert('하나만 올려라.');
        return;
    }

    if (files[0].type.match(/image.*/)) {

        $('#first_modal').css({
            display: 'none'
        });
        $('#second_modal').css({
            display: 'flex'
        });

        $('.img_upload_space').css({
            "background-image": "url(" + window.URL.createObjectURL(files[0]) + ")",
            "outline": "none",
            "background-size": "100%",
            "background-repeat": "no-repeat",
            "background-position": "center"
        });
    } else {
        alert('이미지가 아닙니다.');
        return;
    }

}

$('#button_profile_upload').click(function (){
    $('#input_fileupload').click();
});

function profile_upload(){
    let file = $('#input_fileupload')[0].files[0];

    let email = "{{ user.email }}";

    let fd = new FormData();

    fd.append('file', file);
    fd.append('email', email);

    $.ajax({
        url: "/user/profile/upload",
        data: fd,
        method: "POST",
        processData: false,
        contentType: false,
        success: function (data) {
            console.log("성공");
        },
        error: function (request, status, error) {
            console.log("에러");
        },
        complete: function () {
            console.log("완료");
            location.replace("/content/profile");
        }
    });

}
</script>
{%endblock%}