config/urls.py
from django.contrib import admin
from django.urls import path, include
import user
import content
from django.conf.urls.static import static
from .settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', include('content.urls')),
]
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

content/urls.py
from django.urls import path
from . import views
app_name = 'content'
urlpatterns = [
    path('', views.Main.as_view(), name='index'),
    path('content/profile', views.Profile.as_view(), name='profile'),
    path('content/upload',views.UploadFeed.as_view(), name='upload_feed'),
    path('like/<int:id>', views.like_count, name='like_count')
]

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user'
urlpatterns = [
    path('join', views.Join.as_view(), name='join'),
    path('login', views.Login.as_view(), name='login'),
    path('logout', views.LogOut.as_view(), name='logout'),
    path('profile/upload', views.UploadProfile.as_view(), name='profileUpload'),
]

templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello, Hanstagram~!</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Google Icon -->
    <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
            rel="stylesheet">

    <!-- Jquery -->
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    {% block style %}
    {%endblock%}
    {% csrf_token %}
</head>

<body>
    {% include "common/navbar.html"%}
    {%block content%}
    {%endblock%}
</body>

</html>

templates/common/navbar.html
{% load static %}

<!-- 네비게이션바 -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<!-- Google Icon -->
<link
    href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
    rel="stylesheet">

<!-- Jquery -->
<script src="http://code.jquery.com/jquery-latest.min.js"></script>

<style>
    .profile {
        width: 100%;
        height: 100%;
        object-fit: cover;
    }
</style>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="position: fixed;width: 100%; z-index: 999">
    <div class="container-fluid" style="justify-content: space-between;flex-wrap: nowrap; min-width: 1000px">
        <a class="navbar-brand" href="{% url 'content:index' %}"><img style="width: 100px"
                src="{% static 'img/hanstagram.png'%}">
        </a>
        <input class="form-control me-2" style="width: 400px" type="search" placeholder="Search" aria-label="Search">
        <div style="display: flex">
            <a href="{% url 'content:index' %}" style="color: black">
            <span class="material-icons" style="padding-right: 10px"> home</span></a>
            <span id="nav_bar_add_box" class="material-icons-outlined" style="padding-right: 10px">add_box</span>

            <div class="dropdown">
                <a href="#" class="dropdown-toggle" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                    <div class="box" style="width: 25px; height: 25px">
                        {% if user.is_authenticated %}
                        <img class="profile"
                            src="{% get_media_prefix %}{{ user.profile_image }}">
                        {% else %}
                        <img class="profile"
                            src="{% static 'img/django.png' %}">
                        {% endif %}

                    </div>
                </a>

                <ul class="dropdown-menu" style="left:-158px" aria-labelledby="dropdownMenuLink">
                    {% if user.is_authenticated %}
                    <li><a class="dropdown-item" href="{% url 'content:profile' %}">프로필</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{% url 'user:logout' %}">로그아웃</a></li>
                    {% else %}
                    <li><a class="dropdown-item" href="{% url 'user:login' %}">로그인</a></li>
                    {% endif%}
                </ul>
            </div>          
            
        </div>
    </div>
</nav>